"""`wiro-gateway` CLI: init / doctor / start / printenv."""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

import typer
from rich.console import Console
from rich.panel import Panel
from rich.table import Table

from . import __version__
from .config import get_settings
from .wiro_to_params import merge_messages

app = typer.Typer(add_completion=False, help="wiro-gateway: Claude Code / Codex -> Wiro Qwen3.8-27B-Uncensored")
console = Console()

ENV_PATH = Path.cwd() / ".env"


def _read_env() -> dict[str, str]:
    if not ENV_PATH.exists():
        return {}
    out: dict[str, str] = {}
    for line in ENV_PATH.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if not s or s.startswith("#") or "=" not in s:
            continue
        k, v = s.split("=", 1)
        out[k.strip()] = v.strip()
    return out


def _write_env(values: dict[str, str]) -> None:
    lines = [
        "# Generated by `wiro-gateway init`. Keep this file private (chmod 600).",
        "",
    ]
    for k, v in values.items():
        lines.append(f"{k}={v}")
    ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    try:
        os.chmod(ENV_PATH, 0o600)
    except OSError:
        pass


@app.command()
def init(
    api_key: str | None = typer.Option(None, "--api-key", help="Wiro API key (or paste later)"),
    api_secret: str | None = typer.Option(None, "--api-secret", help="Wiro API secret (or paste later)"),
    model: str = typer.Option("qwen/qwen3-8-27b-uncensored", "--model", help="Default Wiro model path"),
    port: int = typer.Option(8765, "--port", help="Local gateway port"),
    yes: bool = typer.Option(False, "--yes", "-y", help="Don't prompt; use provided flags / .env.example defaults"),
) -> None:
    """Write a fresh .env with your Wiro credentials. Idempotent."""
    current = _read_env()
    if not api_key:
        if current.get("WIRO_API_KEY"):
            api_key = current["WIRO_API_KEY"]
        else:
            api_key = typer.prompt("Wiro API key (from https://wiro.ai/panel -> Projects)")
    if not api_secret:
        if current.get("WIRO_API_SECRET"):
            api_secret = current["WIRO_API_SECRET"]
        else:
            api_secret = typer.prompt("Wiro API secret (Signature-Based projects only)", hide_input=True)
    if current.get("WIRO_MODEL"):
        model = current["WIRO_MODEL"]
    if current.get("GATEWAY_PORT"):
        try:
            port = int(current["GATEWAY_PORT"])
        except ValueError:
            pass

    values = {
        "WIRO_API_KEY": api_key or "",
        "WIRO_API_SECRET": api_secret or "",
        "WIRO_MODEL": model,
        "WIRO_API_BASE": "https://api.wiro.ai/v1",
        "WIRO_WS_BASE": "wss://socket.wiro.ai/v1",
        "GATEWAY_HOST": "127.0.0.1",
        "GATEWAY_PORT": str(port),
        "WIRO_POLL_INTERVAL_SEC": "1.0",
        "WIRO_POLL_TIMEOUT_SEC": "600",
    }
    _write_env(values)
    console.print(Panel.fit(
        f"[green]OK[/green] Wrote [bold]{ENV_PATH}[/bold]\n"
        f"  model : {model}\n  port  : {port}\n"
        "Next: `wiro-gateway doctor` to verify, then `wiro-gateway start`.",
        title="wiro-gateway init",
    ))


@app.command()
def doctor() -> None:
    """Verify config + a tiny Run call against Wiro. Stops on first failure."""
    s = get_settings()
    table = Table(title="wiro-gateway doctor", show_lines=False)
    table.add_column("Check", style="bold")
    table.add_column("Result")
    table.add_column("Detail")
    try:
        s.require_credentials()
        table.add_row("Credentials", "[green]ok[/green]", f"key={s.wiro_api_key[:6]}…")
    except Exception as exc:
        table.add_row("Credentials", "[red]fail[/red]", str(exc))
        console.print(table)
        raise typer.Exit(1)

    import asyncio
    import httpx
    from .auth import auth_headers
    headers = auth_headers(s.wiro_api_key, s.wiro_api_secret)
    try:
        with httpx.Client(timeout=15.0) as c:
            r = c.post(
                f"{s.wiro_api_base}/Run/{s.wiro_model}",
                data={"prompt": "ping", "max_tokens": "8"},
                headers=headers,
            )
        if r.status_code in (200, 201):
            payload = r.json()
            table.add_row(
                "Wiro Run", "[green]ok[/green]",
                f"taskid={payload.get('taskid')} status_endpoint=Task/Detail",
            )
        else:
            table.add_row("Wiro Run", "[red]fail[/red]", f"HTTP {r.status_code}: {r.text[:200]}")
            console.print(table)
            raise typer.Exit(1)
    except Exception as exc:
        table.add_row("Wiro Run", "[red]fail[/red]", str(exc))
        console.print(table)
        raise typer.Exit(1)
    console.print(table)


@app.command()
def start(
    host: str | None = typer.Option(None, "--host"),
    port: int | None = typer.Option(None, "--port"),
    reload: bool = typer.Option(False, "--reload", help="Dev: reload on code change"),
    log_level: str = typer.Option("info", "--log-level"),
) -> None:
    """Start the local FastAPI server (blocking)."""
    s = get_settings()
    s.require_credentials()
    host = host or s.gateway_host
    port = port or s.gateway_port
    import uvicorn
    console.print(f"[bold]wiro-gateway[/bold] {__version__} starting on http://{host}:{port} (model={s.wiro_model})")
    uvicorn.run("wiro_gateway.server:app", host=host, port=port, reload=reload, log_level=log_level)


@app.command(name="printenv")
def printenv() -> None:
    """Print the env vars Codex / Claude Code need to point at the gateway."""
    s = get_settings()
    host = s.gateway_host
    port = s.gateway_port
    base = f"http://{host}:{port}"
    out = {
        "openai": {
            "OPENAI_BASE_URL": f"{base}/v1",
            "OPENAI_API_KEY": "wiro",
        },
        "anthropic": {
            "ANTHROPIC_BASE_URL": base,
            "ANTHROPIC_AUTH_TOKEN": "wiro",
        },
    }
    console.print_json(data=out)


@app.command()
def merge_demo() -> None:
    """Smoke test the message merger without hitting Wiro."""
    msgs = [
        {"role": "system", "content": "You are helpful."},
        {"role": "user", "content": "Hi!"},
        {"role": "assistant", "content": "Hello."},
        {"role": "user", "content": "Tell me a joke."},
    ]
    sys, prompt = merge_messages(msgs, None)
    console.print(Panel(prompt, title="merged prompt", subtitle=f"system={sys[:60]!r}"))


@app.command()
def version() -> None:
    """Print version and exit."""
    console.print(f"wiro-gateway {__version__}")




@app.command()
def install(
    api_key: str | None = typer.Option(None, "--api-key", help="Wiro API key (or paste at the prompt)"),
    api_secret: str | None = typer.Option(None, "--api-secret", help="Wiro API secret (or paste at the prompt)"),
    no_systemd: bool = typer.Option(False, "--no-systemd", help="Skip systemd user service install"),
    no_wrappers: bool = typer.Option(False, "--no-wrappers", help="Skip codexw / qwen-codex wrapper install"),
    non_interactive: bool = typer.Option(False, "--non-interactive", "-y", help="Re-use existing .env, do not prompt"),
) -> None:
    """One-shot install: .env + systemd service + codexw wrapper. Then 'codexw'."""
    # 1. .env
    if not non_interactive or not (Path.cwd() / ".env").exists():
        init(api_key=api_key, api_secret=api_secret, yes=non_interactive)
    # 2. systemd
    if not no_systemd:
        import subprocess
        r = subprocess.run([str(Path(__file__).parent.parent / "bin" / "install-systemd.sh")])
        if r.returncode != 0:
            raise typer.Exit(r.returncode)
    # 3. wrappers
    if not no_wrappers:
        import subprocess
        r = subprocess.run([str(Path(__file__).parent.parent / "bin" / "install-wrappers.sh")])
        if r.returncode != 0:
            raise typer.Exit(r.returncode)
    # 4. healthz
    s = get_settings()
    if s.wiro_api_key and s.wiro_api_secret:
        url = f"http://{s.gateway_host}:{s.gateway_port}/healthz"
        try:
            import httpx
            r = httpx.get(url, timeout=2.0)
            if r.status_code == 200:
                console.print(f"[bold green]OK[/bold green] gateway is live at {url}")
        except Exception:
            console.print(f"[yellow]gateway not yet reachable at {url} (it may start in a moment)[/yellow]")

    console.print()
    console.print(Panel.fit(
        "[bold green]wiro-gateway is installed.[/bold green]\n\n"
        "  Run [bold cyan]codexw[/bold cyan] in any directory to launch Codex with Qwen 3.8 27B.\n"
        "  Or: [bold cyan]codexw exec \"refactor foo.py\"[/bold cyan]\n\n"
        "  Manage:  systemctl --user {status,restart,stop} wiro-gateway\n"
        "  Logs:     tail -f /tmp/wiro-gateway.log\n"
        "  Uninstall: wiro-gateway uninstall",
        title="All set",
    ))


@app.command()
def uninstall(
    purge_config: bool = typer.Option(False, "--purge", help="Also delete the wiro provider/profile in ~/.codex/"),
    yes: bool = typer.Option(False, "--yes", "-y", help="Don't prompt"),
) -> None:
    """Stop and remove the systemd service, the wrappers, and the codex wiro profile."""
    import subprocess
    if not yes:
        typer.confirm("Remove wiro-gateway systemd service and codex wrappers?", abort=True)
    s = Path(__file__).parent.parent / "bin"
    subprocess.run([str(s / "uninstall-systemd.sh")], check=False)
    # Remove symlinks in ~/.local/bin/
    home_bin = Path.home() / ".local" / "bin"
    for name in ("qwen-codex", "codexw", "codex-wiro", "qwen-claude", "claudew", "claude-wiro"):
        p = home_bin / name
        if p.is_symlink() or p.exists():
            try:
                p.unlink()
            except OSError:
                pass
    if purge_config:
        for p in (Path.home() / ".codex" / "wiro.config.toml",):
            if p.exists():
                p.unlink()
                console.print(f"removed {p}")
        # Remove the [model_providers.wiro] block from the main config if present
        main = Path.home() / ".codex" / "config.toml"
        if main.exists():
            text = main.read_text()
            import re
            new = re.sub(r"\n# --- wiro-gateway:.*?(?=\n\[|\Z)", "", text, flags=re.DOTALL)
            if new != text:
                main.write_text(new)
                console.print(f"purged wiro provider from {main}")
    console.print("[green]wiro-gateway uninstalled.[/green]  .env and source files left in place.")



if __name__ == "__main__":
    app()
